"""
Functionality to take logs generated by running simulations, and get final results from them.

Results for algorithm X (according to the name in 'screening_algorithms', below) are stored in X.pickle, as a dictionary {result_type: dictionary of timeseries for that result type and that algorithm, indexed by seed that generated the run}

Functionality to get the following results from timeseries:
-> plotting a quantity over time, with 95% CIs, for a selection of algorithms
-> TBC
"""

###-IMPORTS-###
import os

import hpvsim as hpv
from hpvsim.parameters import get_genotype_pars

import numpy as np
import sciris as sc


from scipy import stats

import pickle

import csv


from basePars import base_pars
from InterventionAlgorithms import NHS_2025_lambdamu, NHS_Vacc

import copy

from tqdm import tqdm

import matplotlib as mpl
import matplotlib.pyplot as plt

from InterventionAlgorithms.simulationLogging import makeLoggingIntervention
from basePars import base_pars

from copy import deepcopy

from colorScheme import natureColorScheme

import seaborn as sns



###-GLOBAL VARIABLES-###
"""
    We define global variables relating to our results here:
    -> significance level for computation of confidence intervals
    -> what screening algorithms we are testing
    -> what results we care to extract
    -> what we are calling everything internally, vs how we label it for plots
"""
sig_level = 0.05


    #screening algorithms labelled either "{x}_{y}" with screening interval x for unvaccinated and y for vaccinated, or '{x}plus{y}' for screening interval x for cohorts not offered vaccination and y for cohorts offered vaccination
    #These names for the algorithms should be shared across the internal logic; used for filenames and indexing any dictionaries that are indexed by screening algorithm type
screening_algorithms = ['5_5', '5_7', '5_10', '5_15', '5_20',
                               '7_7', '7_10', '7_15', '7_20',
                                      '10_10','10_15','10_20',
                                              '15_15','15_20',
                               '5plus7', '5plus10', '5plus15', '5plus20', #NOTE: there is no need to the diagnonal of the matrix here as well, because amounts to identical algorithms as the diagonal of the matrix above
                                         '7plus10', '7plus15', '7plus20',
                                                    '10plus15','10plus20',
                                                               '15plus20',
                        'none_none', #'none' indicates there is no (asymptomatic) screening at all (hence a lack of an interval itself)
                        '5_none',
                        '5plusnone',
]
    #To change the names of screening algorithms as presented in figures/tables/other results, change them here
screening_algorithms_labels = {'5_5':'5:5', 
                               '5_7':'5:7',
                               '5_10':'5:10',
                               '5_15':'5:15', 
                               '5_20':'5:20',
                               '7_7':'7:7',
                               '7_10':'7:10',
                               '7_15':'7:15', 
                               '7_20':'7:20',
                               '10_10':'10:10',
                               '10_15':'10:15', 
                               '10_20':'10:20',
                               '15_15':'15:15', 
                               '15_20':'15:20',

                               '5plus7':'5:5+7:7',
                               '5plus10':'5:5+10:10',
                               '5plus15':'5:5+15:15', 
                               '5plus20':'5:5+20:20',
                               '7plus10':'7:7+10:10',
                               '7plus15':'7:7+15:15', 
                               '7plus20':'7:7+20:20',
                               '10plus15':'10:10+15:15', 
                               '10plus20':'10:10+20:20',
                               '15plus20':'15:15+20:20',

                                'none_none':'No scrn.', 
                                '5_none':'Unvacc individuals only (5:-)',
                                '5plusnone':'Unvacc. cohorts only (5:5+-:-)',
}
#Add low and high vacc as extra logical 'algorithms' (rather than a different heirachical layer of 'vacc. scenario') for simplicity of comparison
for i in range(len(screening_algorithms)):
    screening_algorithm = screening_algorithms[i]
    screening_algorithms.append(f"{screening_algorithm}_LV")
    screening_algorithms_labels[f"{screening_algorithm}_LV"] = f"{screening_algorithms_labels[screening_algorithm]}, LV"
    screening_algorithms.append(f"{screening_algorithm}_HV")
    screening_algorithms_labels[f"{screening_algorithm}_HV"] = f"{screening_algorithms_labels[screening_algorithm]}, HV"


    #Define the internal names of the quantities being recorded over time (i.e. internal timeseries names); 'result-types'
vacc_states = ["_vaccpop", "_unvaccpop", "_allpop"]
genotype_states = ["_vacctype", "_unvacctype", "_alltypes"]
stems_to_be_split_by_genotype_and_vaccstate = [
    "inc_infectious",
    "inc_cin",
    "inc_cancers",
    "inc_cancers_diagnosed", 
    "inc_cancer_deaths",
    "prev_infectious",
    "prev_cin",
    "prev_cancers",
    "prev_cancers_undiagnosed_after_5_years",#
]
stems_to_be_split_by_vaccstate_only = [
    "routine_screens",
    "popsize"
]

data_names = []
for stem in stems_to_be_split_by_genotype_and_vaccstate:
    for vacc_state in vacc_states:
        for genotype_state in genotype_states:
            data_names.append(stem+vacc_state+genotype_state)
for stem in stems_to_be_split_by_vaccstate_only:
    for vacc_state in vacc_states:
        data_names.append(stem+vacc_state)


     #    DO THIS NEXT:   any timeseries in my existing logging functionality useful and an i jsut add that to the pickle files, indexed by seed ? then theres some more where i can use the existing thing but make sepreat timeseries by genotype and then save them in ig? or do they need to be serpeated by genotype here, maybe just have lists from the numpy arrays?






###-RECORDING SIMULATION RESULTS AS TIMESERIES-###
"""
    Each simulation's log cotains a lot of data - we condense this into dictionaries of timeseries.
    We generate a 'timeseries' (a list - not a dictionary) for each quantity of interest from each simulation, and index the timeseries by properties of the simulation that allow for pairing (for paired t tests).
    Timeseries are stored in .pickle files, where there is one .pickle file for each algorithm
"""
def initialise_blank_ts_file(algs = None):
    """
    Initialises blank timeseries (ts) files for the specified algorithms (if alg=None, does for all algorithms)
    """
    if algs is None:
        algs = screening_algorithms
    
    for alg in algs:
        data = {}
        for data_name in data_names:
            data[data_name] = {} #to be populated as {(seed, paramaterisation_num): timeseries of the given data_name, for this algorithm, when running with this seed}
        
        
        filename = f'{alg}.pickle'

        follow_through_on_saving = False #a safety check to make sure we don't accidentally override an existing log
        if os.path.isfile(filename):
            override = input(f"File {filename} already exists. Press (y) to override, any other key to skip initialising this timeseries file.")
            if override.lower() == 'y':
                follow_through_on_saving=True
        else:
            follow_through_on_saving=True

        if follow_through_on_saving:
            with open(filename,'wb') as file:
                pickle.dump(data, file)
            print(f"Made file {filename}.")
        else:
            print("Skipping initialisation of timeseries file, due to a file with this name already existing and the file override option not being selected")


def save_timeseries_from_log(log, seed, parameterisation_num, alg):
    """
    Gets results from {log}, generated by running a simulation with screening algorithm alg<-screening_algorithms and seed {seed}, and adds the results from this run to the result file, with each result indexed by seed.
    """
    filename = f"{alg}.pickle"
    #Load in file we will be adding the timeseries to
    try:
        with open(filename,'rb') as file:
            data = pickle.load(file) 
            print("Successfully loaded data file, and will be adding processed timeseries to this file.")
    except:
        print("No data file found to add data to. Exiting programme to avoid damage to any saved data.")
        quit(0)

    #Generate the timeseries
    timeserieses = get_timseries_from_log(log)

    #For each timeseries in timeseriess, add it (with the seed and the parameter set used for HPVsim as an index) to the log
    for data_name in data_names:
        data[data_name][(seed, parameterisation_num)] = timeserieses[data_name]

    #Save
    with open(filename,'wb') as file:
        pickle.dump(data, file)
    

def make_logging_intervention_for_result_gen():
    """
    Returns  (function to pass as an intervention with which to do logging, dictionary info will be logged to), for the only interventions we need to be tracking for the results we are amassing
    """
    return makeLoggingIntervention(trackable_interventions_by_label = ['routine_screening_under50',
                                                                       'routine_screening_50andover',
                                                                       'colposcopy'])

def get_timseries_from_log(log, rescale_factor = 1/1.19):
    """
    rescale_factor: we rescale all scales by this (multiplication); accounts for our modelling of the England population as 1/1.19x the UK population 

    Takes {log}, generated from running a simulation, and extracts quantities to populate each timeseries specified in data_names.
    Returns a dictionary of results indexed by timeseries name (i.e. element in data_names)
    """
    timeseries = {result_type: [] for result_type in data_names} #we add an element to each list for each timepoint we iterate over in the log

    #Takes a np array of form (n_genotypes, pop_size) and collapses it to (pop_size) by OR-ing over the genotypes we care about for particular quantities
    genotype_collapser_from_genotype_state = {
        "_vacctype": (lambda genotype_wise_results: np.any(genotype_wise_results[:3,:], axis=0)), #take the first three rows (these are vaccine genotypes) and then collapse over the genotype column over these remianing genotypes - any 'True's mean presence of this state in some genotype
        "_unvacctype": (lambda genotype_wise_results: np.array(genotype_wise_results[3,:], dtype=bool)), #take the row of 'ohr' type, and ensure it is the boolean type
        "_alltypes": (lambda genotype_wise_results: np.any(genotype_wise_results, axis=0)), #'or' over all genotypes
    }


    #Templates of trackers of simulation state between timepoints
        #cumulative trackers (at the start of each loop, keeps track of a cumualtive state up to the end of the previous loop)
    cumulative_pids_diagnosed_with_cancer = set() #keeps track of all pids diagnosed with cancer at a given timepoint; once diagnosed, even if treated, we keep them in this set in regognistion of increased followup +attention post-treatment, to reduce inflation in 'undiagnosed cancers after 5 years' for repeat cancers as likely this is a modelling artifact from our only modelling diagnosis through regular screening 
        
        #previous-timestep trackers (at the start of each loop, keeps track of state at the end of the previous loop)- for calculating incidence
    previous_timestep_infectious = np.array([]) #a 1D empty array (1D with no elements)
    previous_timestep_cin = np.array([]) 
        
        #5-year-ago trackers (at the start of loop t, has the state as of the end of loop t-5/dt)
    timepoint_lag_5yr = int(5/base_pars['dt']) #number of timepoints that make up a 5-year lag (this will not be exact unless 1/dt is an int)
    pids_with_cancer_iplus1_timepoints_ago = [set() for i in range(timepoint_lag_5yr)] 
            #^ At the start of timepoint t, element i stores all agents who had cancer at the end of timepoint t-(i+1), and continually since then to the start of timepoint t.
            #Each timepoint, we are to (1) shift everything up one index by adding currently cancerous agents to the start of the list, and
            #                          (2) filter the list's sets to only incldue those with continual cancer, using INTERSECTION operations to ensure elemnnt i+1 is always contianed in element i
            #                          (3) take the final element of the list, which is people who have had cancer continually for 5 years, are checked against those diagnosed to track the number of undiagosed after 5 years of continual cancer
            #NOTE: final element of loist is all pids with cancer that still have it and it is at least 5 years old; when we pop from the end we still put elements back into that last set again, we are essentially just combining the final two sets at each time a new set starts at the front of the list and works its way to the set of long-term cancerous agents at the back
            #We note that we do not record 'previous_timestep_pids_with_cin', as that is 'pids_with_cancer_iplus1_timepoints_ago[0]' at the start of a timestep
    
    #Specific trackers for simulation state between timepoints, indexed by population and genotype of interest
    state_trackers = {}
    for vacc_state in vacc_states:
        for genotype_state in genotype_states:
            state_trackers[vacc_state+genotype_state] = [
                deepcopy(cumulative_pids_diagnosed_with_cancer),
                deepcopy(previous_timestep_infectious),
                deepcopy(previous_timestep_cin),
                deepcopy(pids_with_cancer_iplus1_timepoints_ago)
            ]
    previous_n = 0 

    for t in sorted(log.keys()):
        log_at_timepoint = log[t]

        #Get which agents are vaccinated/unvaccinated
        vacc_by_pid = log_at_timepoint['vx_doses']>=1
        unvacc_by_pid = ~vacc_by_pid

        #Get the scale of each agent (we assign any agent which is not female or not alive a scale of 0, so that when we aggregate agent's sacles to get number over a population, we stay within the subpopulation of interest)
        scale_by_pid = log_at_timepoint['scale'] * rescale_factor
        scale_by_pid = np.multiply(scale_by_pid, log_at_timepoint['alive'])
        scale_by_pid = np.multiply(scale_by_pid, log_at_timepoint['sex']==0) #a sex of 0 means female


        n = log_at_timepoint['n']

        
        #Infectiousness tracking: "inc_infectious", "prev_infectious". Uses, then updates 'previous_timestep_pids_with_infectiousness'
        current_infectious = log_at_timepoint['infectious']

        for genotype_state in genotype_states:    #We loop through all considered 'scopes' of analysis in terms of genotypes of interst and subpopulations of interest
            #Restrict our focus down to the genotype of interest
            current_infectious_genotypescollapsed = genotype_collapser_from_genotype_state[genotype_state](current_infectious)
            for vacc_state in vacc_states:
                #Restrict our focus down to the population of interest (make all others 'false')
                if vacc_state == '_vaccpop':
                    current_infectious_of_interest = np.logical_and(current_infectious_genotypescollapsed, vacc_by_pid)
                elif vacc_state == '_unvaccpop':
                    current_infectious_of_interest = np.logical_and(current_infectious_genotypescollapsed, unvacc_by_pid)
                elif vacc_state == '_allpop':
                    current_infectious_of_interest = current_infectious_genotypescollapsed
                else:
                    print("Unrecognised vacc state")
                    assert False
                
                #Calculate incidence - infections that are now that were not before
                previous_infectious_of_interest = state_trackers[vacc_state+genotype_state][1]
                newly_infected_existing_agents = np.dot(current_infectious_of_interest[:previous_n] > previous_infectious_of_interest, #there is a 'true' for each time an agent is newly infected, for those that existed before, and we add them up to get a count
                                                        scale_by_pid[:previous_n] #dot-multiply by each agent's scale so we add up the number of people represented by each newly infectious agent
                                                    )
                newly_infected_new_agents = np.dot(current_infectious_of_interest[previous_n:], scale_by_pid[previous_n:])
                incidence = newly_infected_existing_agents + newly_infected_new_agents
                timeseries['inc_infectious'+vacc_state+genotype_state].append(incidence)

                #Calculate prevalence
                prevalence = np.dot(current_infectious_of_interest, scale_by_pid)
                timeseries['prev_infectious'+vacc_state+genotype_state].append(prevalence)
                
                #Update state tracker of infectiousness prevalence at each 'previous timepoint'
                state_trackers[vacc_state+genotype_state][1] = current_infectious_of_interest #don't need to do a deep copy of this array as we immediately are moving onto a different array after this loop, and are never changing the values in here anyway
    

        #CIN tracking: "inc_cin", "prev_cin". Uses, then updates 'previous_timestep_pids_with_cin'
        current_cin = log_at_timepoint['cin']

        for genotype_state in genotype_states:  #We loop through all considered 'scopes' of analysis in terms of genotypes of interst and subpopulations of interest
            #Restrict our focus down to the genotype of interest
            current_cin_genotypescollapsed = genotype_collapser_from_genotype_state[genotype_state](current_cin)
            for vacc_state in vacc_states:
                #Restrict our focus down to the population of interest (make all others 'false')
                if vacc_state == '_vaccpop':
                    current_cin_of_interest = np.logical_and(current_cin_genotypescollapsed, vacc_by_pid)
                elif vacc_state == '_unvaccpop':
                    current_cin_of_interest = np.logical_and(current_cin_genotypescollapsed, unvacc_by_pid)
                elif vacc_state == '_allpop':
                    current_cin_of_interest = current_cin_genotypescollapsed
                else:
                    print("Unrecognised vacc state")
                    assert False
                
                #Calculate incidence - cins that are now that were not before
                previous_cin_of_interest = state_trackers[vacc_state+genotype_state][2]
                newly_cin_existing_agents = np.dot(current_cin_of_interest[:previous_n] > previous_cin_of_interest, #there is a 'true' for each time an agent is newly infected, for those that existed before, and we add them up to get a count
                                                        scale_by_pid[:previous_n] #dot-multiply by each agent's scale so we add up the number of people represented by each newly infectious agent
                                                    )
                newly_cin_new_agents = np.dot(current_cin_of_interest[previous_n:], scale_by_pid[previous_n:])
                incidence = newly_cin_existing_agents + newly_cin_new_agents
                timeseries['inc_cin'+vacc_state+genotype_state].append(incidence)

                #Calculate prevalence
                prevalence = np.dot(current_cin_of_interest, scale_by_pid)
                timeseries['prev_cin'+vacc_state+genotype_state].append(prevalence)
                
                #Update state tracker of cin prevalence at each 'previous timepoint'
                state_trackers[vacc_state+genotype_state][2] = current_cin_of_interest #don't need to do a deep copy of this array as we immediately are moving onto a different array after this loop, and are never changing the values in here anyway
    

        #Cancer tracking: "inc_cancers", "prev_cancers". Uses pids_with_cancer_iplus1_timepoints_ago[0].
        current_cancerous = log_at_timepoint['cancerous']

        for genotype_state in genotype_states:  #We loop through all considered 'scopes' of analysis in terms of genotypes of interst and subpopulations of interest
            #Restrict our focus down to the genotype of interest
            current_cancers_genotypescollapsed = genotype_collapser_from_genotype_state[genotype_state](current_cancerous)
            for vacc_state in vacc_states:
                #Restrict our focus down to the population of interest (make all others 'false')
                if vacc_state == '_vaccpop':
                    current_cancers_of_interest = np.logical_and(current_cancers_genotypescollapsed, vacc_by_pid)
                elif vacc_state == '_unvaccpop':
                    current_cancers_of_interest = np.logical_and(current_cancers_genotypescollapsed, unvacc_by_pid)
                elif vacc_state == '_allpop':
                    current_cancers_of_interest = current_cancers_genotypescollapsed
                else:
                    print("Unrecognised vacc state")
                    assert False
                
                #Calculate cancer incidence - cins that are now that were not before
                pids_with_cancer_iplus1_timepoints_ago = state_trackers[vacc_state+genotype_state][3] #a list of nested sets
            
                pids_with_cancer_at_previous_timepoint = pids_with_cancer_iplus1_timepoints_ago[0]
                pids_currently_with_cancer = set(np.where(current_cancers_of_interest)[0]) #a set of the pids of all agents currently suffering with cancer

                pids_newly_with_cancer = pids_currently_with_cancer - pids_with_cancer_at_previous_timepoint
                pids_newly_with_cancer = list(pids_newly_with_cancer) #convert to a list to do fancy indexing
                incidence = np.sum(scale_by_pid[pids_newly_with_cancer])
                timeseries['inc_cancers'+vacc_state+genotype_state].append(incidence)

                #Calculate cancer prevalence
                prevalence = np.sum(scale_by_pid[list(pids_currently_with_cancer)])
                timeseries['prev_cancers'+vacc_state+genotype_state].append(prevalence)
                
                #Update pids_with_cancer_iplus1_timepoints_ago to include current prevalence and be consistent 
                pids_with_cancer_iplus1_timepoints_ago = [pids_currently_with_cancer] + pids_with_cancer_iplus1_timepoints_ago
                for i in range(1,len(pids_with_cancer_iplus1_timepoints_ago)):
                    #To be consistent, each set in this list of sets can only incldue elements in its first set (as if an agent is not cancerous currently, it can't have been continually cancerous from any past point all the way to now, and by enforcing this every time we change the list we ensure the list is one of fully nested sets)
                    pids_with_cancer_iplus1_timepoints_ago[i] = pids_currently_with_cancer.intersection(pids_with_cancer_iplus1_timepoints_ago[i])

                #Calculate number of cancer diagnoses and update state tracker of cumulative set of cancer-diangosed pids 
                current_cancer_diagnosis_set = set(log_at_timepoint['interventions']['colposcopy']['cancer'])
                state_trackers[vacc_state+genotype_state][0] = state_trackers[vacc_state+genotype_state][0].union(current_cancer_diagnosis_set)
                new_diagnoses = np.sum(scale_by_pid[list(current_cancer_diagnosis_set)])
                timeseries['inc_cancers_diagnosed'+vacc_state+genotype_state].append(new_diagnoses)

                #Calcuate number undiagnosed after 5 years (cutoff: does NOT include those diagnosed exactly 5 years of timesteps after development of cancer)
                cancers_after_5_years_or_more = pids_with_cancer_iplus1_timepoints_ago.pop(-1) #get the pids of agents who have had cancer for over 5 years
                pids_with_cancer_iplus1_timepoints_ago[-1] = pids_with_cancer_iplus1_timepoints_ago[-1].union(cancers_after_5_years_or_more) #re-combine so we keep tracking all agents with cancer until they are cured
                
                undiagnosed_cancers_after_5_years_or_more = cancers_after_5_years_or_more - current_cancer_diagnosis_set
                undiagnosed_cancers_after_5_years_or_more = np.sum(scale_by_pid[list(undiagnosed_cancers_after_5_years_or_more)]) #I have defined scale_by_pid not to assign weight to agents who are no longer alive
                timeseries['prev_cancers_undiagnosed_after_5_years'+vacc_state+genotype_state].append(undiagnosed_cancers_after_5_years_or_more)

                #Update state tracker of cancers over the last 5 years of timepoints
                state_trackers[vacc_state+genotype_state][3] = pids_with_cancer_iplus1_timepoints_ago #don't need to do a deep copy of this array as we immediately are moving onto a different array after this loop, and are never changing the values in here anyway
    

        #Population size tracking: "popsize"
        timeseries['popsize'+"_vaccpop"].append(np.dot(scale_by_pid, vacc_by_pid))
        timeseries['popsize'+"_unvaccpop"].append(np.dot(scale_by_pid, unvacc_by_pid))
        timeseries['popsize'+"_allpop"].append(np.sum(scale_by_pid))

        #Screening tracking: "routine_screens"
            #Get test results (note 'over 50' is inclusive, 'under 50' exclusive)
        under50_positives = log_at_timepoint['interventions']['routine_screening_under50']['positive']
        under50_inadequates = log_at_timepoint['interventions']['routine_screening_under50']['inadequate']
        under50_negatives = log_at_timepoint['interventions']['routine_screening_under50']['negative']
        over50_positives = log_at_timepoint['interventions']['routine_screening_50andover']['positive']
        over50_inadequates = log_at_timepoint['interventions']['routine_screening_50andover']['inadequate']
        over50_negatives = log_at_timepoint['interventions']['routine_screening_50andover']['negative']

        for vacc_state in vacc_states:
            #Restrict our focus down to the population of interest by furthering filtering down our scale
            if vacc_state == '_vaccpop':
                filtered_scale = np.multiply(scale_by_pid,vacc_by_pid)
            elif vacc_state == '_unvaccpop':
                filtered_scale = np.multiply(scale_by_pid,unvacc_by_pid)
            elif vacc_state == '_allpop':
                filtered_scale = scale_by_pid
            else:
                print("Unrecognised vacc state")
                assert False

            total_screens = 0
            total_screens += np.sum(filtered_scale[under50_positives])
            total_screens += np.sum(filtered_scale[under50_inadequates])
            total_screens += np.sum(filtered_scale[under50_negatives])
            total_screens += np.sum(filtered_scale[over50_positives])
            total_screens += np.sum(filtered_scale[over50_inadequates])
            total_screens += np.sum(filtered_scale[over50_negatives])

            timeseries['routine_screens'+vacc_state].append(np.sum(total_screens))


        #Update previous n
        previous_n = n

    return timeseries


def smooth_list(xs, smoothing_width):
    xs_smoothed = []
    for i in range(len(xs)):
        av = 0
        for j in range(smoothing_width):
            if i+j<len(xs):
                av += xs[i+j]
        av/=smoothing_width
        xs_smoothed.append(av)
    return xs_smoothed

def plot_quant_over_time(ax, 
                         data_name, normalise_per_100k = True,
                         algs=None, show_quartiles = False, show_normal_CI = False,
                         alg_colors={}, alg_labels={},
                         burnin_timesteps=4*20, burnout_timesteps = 4*5, smoothing_kernel=4):
    """
    ax: matplotlib.pyplot Axis object on which to plot
    data_name: what is to be plotted on the y axis (data_name<-data_names)
    normalise_per_100k: whether to plot all data per 100k members of the population from which data_name is taken (all agents, all vaccinated agents, or all unvaccinated agents)

    algs: the algorithms to be plotted (algs is to be a subset of screening_algorithms)
    show_quartiles: if True, plots median curve at each timepoint bounded by LQ and UQ. 
    show_normal_CI: If True, plots mean and the t-test confidence interval around the mean.
        NOTE: show_quartiles and show_normal_CI cannot simultaneously be true

    alg_colors (dict): dictionary mapping elements of algs to colors for their matplotlib plotting. If None, sticks with default matplotlib colors
    alg_labels (dict): dictionary mapping elements of algs to names for them for thier matplotlib plotting. If left as default, sticks with internal names as in algs

    burnin_timesteps: the number of timesteps to ignore at the start of the plot, for burnin
    burnout_timesteps: the number of timesteps to ignore at the end of the plot, s.t. post-moving-average-smoothing we don't get an incorrect dropoff at the end of the plot (if 0, no burnout)
    smoothing_kernel: width (in timesteps) of moving average filter over timeseries
    """
    #Deal with parameters (assign defaults and check correctness)
    if algs is None:
        algs = deepcopy(screening_algorithms)

    assert not (show_quartiles and show_normal_CI)

    assert data_name in data_names
    for alg in algs:
        assert alg in screening_algorithms
        
    assert burnin_timesteps>=0
    assert burnout_timesteps>=0
    
    #Extract what our population of interest is
    pop = None
    if data_name.find("_allpop") != -1:
        pop = "popsize_allpop"
    elif data_name.find("_vaccpop") != -1:
        pop = "popsize_vaccpop"
    elif data_name.find("_unvaccpop") != -1:
        pop = "popsize_unvaccpop"
    else:
        print(f"Data name {data_name} has not been found invalid but does not specified a calculable denominator population. Major error.")
        assert False

    #Load and process relevant data from files
    lower_timeseries_by_alg = {}
    middle_timeseries_by_alg = {} 
    upper_timeseries_by_alg = {} 
    for alg in algs:
        try:
            #Load file
            with open(f"{alg}.pickle", "rb") as f:
                loaded_data = pickle.load(f)
                alg_timeseriess = loaded_data[data_name] #alg_timeseries = {(seed, parametersation):[timeseries]}
                pop_timeseriess = loaded_data[pop]

            #Preprocess loaded timeserieses for easy computation of mean/std over timepoints (turn into numpy array)
            alg_timeseriess_array = []
            pop_size_array = []
            for key in alg_timeseriess.keys(): #iterate over (seed, parametersation) pairs, as this plotting does not need them as it does not do paired comparisons
                alg_timeseriess_array.append(alg_timeseriess[key])
                pop_size_array.append(pop_timeseriess[key]) #timeseries with the same (seed, parameterisation) pair have corresponding positions in alg_timeseriess_array and pop_size_array
            
            alg_timeseriess_array = np.array(alg_timeseriess_array) #shape (#timeseries, #timepoints in each timeseries)
            pop_size_array = np.array(pop_size_array)
            n,T = alg_timeseriess_array.shape
            #print(n)

            #Normalise point-wise if desired
            if normalise_per_100k:
                alg_timeseriess_array = np.divide(alg_timeseriess_array, pop_size_array) * 100_000 #multiply by 100k to get rate per 100k 

            #compute lb, m, ub to be the timeseries of lower bounds, middles, and upper bounds respectively for this alg
            if show_quartiles:
                lb, m, ub = [],[],[]
                lb = list(np.percentile(alg_timeseriess_array, 25, axis=0))
                ub = list(np.percentile(alg_timeseriess_array, 75, axis=0))
                m = list(np.percentile(alg_timeseriess_array, 50, axis=0))
            else: 
                #Compute means, stds
                means = np.mean(alg_timeseriess_array, axis=0)
                stds = np.std(alg_timeseriess_array, axis=0, ddof=1)

                #Compute confidence intervals (timepoint-wise) and add relevant timeseries to the dictionary to be plotted
                lb, ub = [], []; m = list(means)
                for t in range(T):
                    ci = stats.t.interval(
                        1-sig_level,
                        df = n-1,
                        loc = means[t],
                        scale = stds[t]/np.sqrt(n)
                    )
                    lb.append(ci[0]); ub.append(ci[1])

            lower_timeseries_by_alg[alg] = lb
            middle_timeseries_by_alg[alg] = m
            upper_timeseries_by_alg[alg] = ub            
        except Exception as e:
            print(f"Unable to open and/or process file {alg}.pickle. Omitting from plot")
            print(e)
            algs.remove(alg)

    #Smooth
    if smoothing_kernel>1:
        for alg in algs:
            lower_timeseries_by_alg[alg] = smooth_list(lower_timeseries_by_alg[alg], smoothing_kernel)
            middle_timeseries_by_alg[alg] = smooth_list(middle_timeseries_by_alg[alg], smoothing_kernel)
            upper_timeseries_by_alg[alg] = smooth_list(upper_timeseries_by_alg[alg], smoothing_kernel)

    #Plot
    for alg in algs: #algs has had any elements removed for which we could not successfully load and process data
        T = len(lower_timeseries_by_alg[alg])
        middles = middle_timeseries_by_alg[alg][burnin_timesteps:T-burnout_timesteps]
        xs = range(len(middles))

        if show_normal_CI or show_quartiles:
            lowers = lower_timeseries_by_alg[alg][burnin_timesteps:T-burnout_timesteps]
            uppers = upper_timeseries_by_alg[alg][burnin_timesteps:T-burnout_timesteps]
            ax.fill_between(xs, lowers, uppers, alpha=0.1, color=alg_colors[alg] if alg in alg_colors.keys() else None)
            ax.plot(xs, lowers, color=alg_colors[alg] if alg in alg_colors.keys() else None, linestyle='dotted', alpha=0.5)
            ax.plot(xs, uppers, color=alg_colors[alg] if alg in alg_colors.keys() else None, linestyle='dotted', alpha=0.5)
        ax.plot(xs, middles, color=alg_colors[alg] if alg in alg_colors.keys() else None, label= alg_labels[alg] if alg in alg_labels.keys() else alg) #TODO: add labels so that we can select to have teh legend on as an optional argument (or just outside the calling of the function)
    return ax

    #TODO: make a global dictioanry mapping alg_name to a colour for plotting with a consistet colour scheme across all this script 


def get_paired_difference_tss(data_name, normalise_per_100k,
                              compared_alg, baseline_alg,
                              ):
    '''
    Returns a list of timeseriess of the paired (by parameterisation and seed) differences between the provided pair of algorithms for the specified quantity.
    data_name (str): the name of timeseries we will be returning paired differences of
    normalise_per_100k (bool): whether to deal with the timeseries in terms of raw numbers, or as rates
    compared_alg (str): the name of the algorithm from whose results we will be subtracting values to get the differences (X in X-Y)
    baseline_alg (str): the name of the algorithm whose results we use to subtract with (Y in X-Y)
    
    Returns:    dict( (seed, param):[timeseries of differences] for each param-seed pair that is successfully paired between the two algs ), 
                set(unpaired param-seed pairs for compared), 
                set(unpaired param-seed pairs for baseline)
    '''
    #Check correctness of parameters
    assert data_name in data_names
    assert compared_alg in screening_algorithms
    assert baseline_alg in screening_algorithms

    #Extract what our population of interest is (we will only use the pop variable if {normalise_per_100k})
    pop = None
    if data_name.find("_allpop") != -1:
        pop = "popsize_allpop"
    elif data_name.find("_vaccpop") != -1:
        pop = "popsize_vaccpop"
    elif data_name.find("_unvaccpop") != -1:
        pop = "popsize_unvaccpop"
    else:
        print(f"Data name {data_name} has not been found invalid but does not specified a calculable denominator population. Major error.")
        assert False

    #Load data from each alg (from both algs, load population over time and the quantity of interest, {data_name}, over time)
    compared_timeseries, baseline_timeseries = None, None #timeseries are of the form {(seed, parameterisation index): [list of values as they vary over timepoints]}
    compared_pops, baseline_pops = None, None
    try:
        with open(f"{compared_alg}.pickle", "rb") as f:
            loaded_data = pickle.load(f)
            compared_timeseries = loaded_data[data_name]
            if normalise_per_100k:
                compared_pops = loaded_data[pop]

        with open(f"{baseline_alg}.pickle", "rb") as f:
            loaded_data = pickle.load(f)
            baseline_timeseries = loaded_data[data_name] 
            if normalise_per_100k:
                baseline_pops = loaded_data[pop]

        assert compared_timeseries is not None
        assert baseline_timeseries is not None
        if normalise_per_100k:
            assert compared_pops is not None
            assert baseline_pops is not None
    except:
        print("Unable to open one of the required timeseries")

    #Convert each timeseries to numpy array for ease of operations, and normalise per 100k if relevant
    if normalise_per_100k:
        for seed, param_index in compared_timeseries.keys():
            raw_values = np.array(compared_timeseries[(seed, param_index)])
            pop_sizes = np.array(compared_pops[(seed, param_index)])
            normalised_values = raw_values/pop_sizes * 100_000
            compared_timeseries[(seed, param_index)] = normalised_values

        for seed, param_index in baseline_timeseries.keys():
            raw_values = np.array(baseline_timeseries[(seed, param_index)])
            pop_sizes = np.array(baseline_pops[(seed, param_index)])
            normalised_values = raw_values/pop_sizes * 100_000
            baseline_timeseries[(seed, param_index)] = normalised_values
    else:
        for seed, param_index in compared_timeseries.keys():
            compared_timeseries[(seed, param_index)] = np.array(compared_timeseries[(seed, param_index)])

        for seed, param_index in baseline_timeseries.keys():
            baseline_timeseries[(seed, param_index)] = np.array(baseline_timeseries[(seed, param_index)])

    #Compute timeserieses of differences
    difference_timeserieses = dict()
    unmatched_compared = set()
    for seed, param_index in compared_timeseries.keys():
        if (seed, param_index) in baseline_timeseries.keys():
            difference_timeserieses[(seed, param_index)] = compared_timeseries[(seed, param_index)] - baseline_timeseries[(seed, param_index)]
        else:
            unmatched_compared.add((seed, param_index))         
    unmatched_baseline = set(baseline_timeseries.keys()) - set(difference_timeserieses.keys())

    return difference_timeserieses, unmatched_compared, unmatched_baseline

def get_simple_totals(data_name, start_tp = 0, end_tp=0, 
                        normalise_per_100k=False, algs=[] ):
    """
    For each algorithm in algs, returns a list of all the sums between start_tp and end_tp (inclusive) for data_name. Formatted as a dictionary.

    data_name (str): the name of timeseries we will be returning sums of
    start_tp: inclusive bound for the start of the sum
    end_tp: inclusive bound for the end of the sum
    normalise_per_100k (bool): whether to deal with the timeseries in terms of raw numbers, or as rates
    algs: the screening algorithms to calculate for
    
    Returns:  {alg: [totals of data_name between timepoints [start_tp, end_tp] for alg in algs]}
    """
    #Check correctness of parameters
    assert data_name in data_names
    assert start_tp>=0 and start_tp<=end_tp
    for alg in algs:
        assert alg in screening_algorithms

    #Extract what our population of interest is (we will only use the pop variable if {normalise_per_100k})
    pop = None
    if data_name.find("_allpop") != -1:
        pop = "popsize_allpop"
    elif data_name.find("_vaccpop") != -1:
        pop = "popsize_vaccpop"
    elif data_name.find("_unvaccpop") != -1:
        pop = "popsize_unvaccpop"
    else:
        print(f"Data name {data_name} has not been found invalid but does not specified a calculable denominator population. Major error.")
        assert False

    #Compute the totals, algorithm-by-algorithm
    totals_by_alg = {alg:[] for alg in algs}
    for alg in tqdm(algs):
        try:
            #Load data: load both population over time and quantity of interest ({data_name}) over time 
            data_timeseries = None #these are of the form {(seed, parameterisation index): [list of values consittuing the timeseries from the simulation with that seed and parameterisation]}
            pop_timeseries = None

            with open(f"{alg}.pickle", 'rb') as f:
                loaded_data = pickle.load(f)
                data_timeseries = loaded_data[data_name]
                if normalise_per_100k:
                    pop_timeseries = loaded_data[pop]
            
            #Check the loaded data is correct (i.e. the data we were looking for was in the file we wanted it to be in)
            assert data_timeseries is not None
            if normalise_per_100k:
                assert pop_timeseries is not None


            
            #Compute totals
            for seed, param_index in data_timeseries.keys():
                #Convert this loaded timeseries to numpy array for ease of operations, normalising if needed
                vs = np.array(data_timeseries[(seed, param_index)])
                if normalise_per_100k:
                    pop_sizes = np.array(pop_timeseries[(seed, param_index)])
                    vs = vs/pop_sizes * 100_000
                
                #Compute total for this loaded timeseries
                total = sum(vs[start_tp: end_tp+1])
                totals_by_alg[alg].append(total)

        except:
            print(f"Error processing  alg {alg}")

    return totals_by_alg


def plot_sum_barchart(ax, bar_colors, line_colors,
                            data_name, start_tp = 0, end_tp=0, 
                            normalise_per_100k=False, algs=[], 
                     xs=None, width=0.8,
                      hatch=None):
    """
    As get_simple_totals, but then takes the totals and plots them as bars to {ax}. Bar heights are medians and upper and lower quartiles indicated by superimposed error bars.
    Bar positions given by xs, widths by {width}.
    Bar colors given by bar_colors, while colours for any lines on the bars given by line_colors. Hatching pattern given by hatch.
    """

    #Get totals
    totals_by_alg = get_simple_totals(data_name, start_tp, end_tp, normalise_per_100k, algs)

    #Get values to be plotted for each alg (ordered according to ordering defined in {algs})
    LQs = [np.percentile(totals_by_alg[alg], 25) for alg in algs]
    medians = [np.median(totals_by_alg[alg]) for alg in algs]
    UQs = [np.percentile(totals_by_alg[alg], 75) for alg in algs]

    #Turn colors into lists with ordering to match {algs}
    bar_colors = [bar_colors[alg] for alg in algs]
    line_colors = [line_colors[alg] for alg in algs]

    #Sort out x axis
    if xs is None:
        xs = list(range(len(algs)))
    ax.set_xticks(xs)
    ax.set_xticklabels(algs)

    #Plot
    ax.bar(xs if xs is not None else range(len(algs)),
            medians, width=width, color=bar_colors, edgecolor=line_colors, hatch=hatch)
    for i in range(len(LQs)):
        ax.errorbar([xs[i]], [medians[i]], yerr=([medians[i] - LQs[i]], [UQs[i]- medians[i]]), capsize=3, color='black')

def plot_sum_barchart_all_vacc_levels(ax, alg_colors,
                                            data_name, start_tp = 0, end_tp=0, 
                                            normalise_per_100k=False, algs=[]):
    """
    As plot_sum_barchart but does a barchart that covers all vaccination uptake levels (60,80,90) and compares them. Some parameters from plot_sum_barchart removed in this function because they are hardcoded within this function to show the different vaccine levels nicely
    """
    bar_colors = {}
    for alg in alg_colors.keys():
        color = deepcopy(alg_colors[alg])
        color += "40" #"40" is 25% in hex, which refers to 0.25 alpha
        bar_colors[alg] = color

    #Plot for 80% vaccination
    plot_sum_barchart(ax, bar_colors, alg_colors, 
                      data_name, start_tp, end_tp, normalise_per_100k, algs, 
                      xs = [x + 0.3 for x in np.arange(len(algs))],
                      width=0.2, hatch="xxxx")
    
    #Now change over to LV
    algstoplot_LV = []
    alg_colors_LV = {}
    bar_colors_LV = {}

    for alg in algs:
        alg_LV = f"{alg}_LV"
        algstoplot_LV.append(alg_LV)
        alg_colors_LV[alg_LV] = alg_colors[alg]
        bar_colors_LV[alg_LV] = bar_colors[alg]

    plot_sum_barchart(ax, bar_colors_LV, alg_colors_LV, 
                      data_name, start_tp, end_tp, normalise_per_100k, algstoplot_LV, 
                      xs = np.arange(len(algstoplot)),
                      width=0.2, hatch="////")
    
    #Now change over to HV
    algstoplot_HV = []
    alg_colors_HV = {}
    bar_colors_HV = {}

    for alg in algs:
        alg_HV = f"{alg}_HV"
        algstoplot_HV.append(alg_HV)
        alg_colors_HV[alg_HV] = alg_colors[alg]
        bar_colors_HV[alg_HV] = bar_colors[alg]

    plot_sum_barchart(ax, bar_colors_HV, alg_colors_HV, 
                      data_name, start_tp, end_tp, normalise_per_100k, algstoplot_HV, 
                      xs = [x + 0.6 for x in np.arange(len(algstoplot))],
                      width=0.2, hatch="\\\\\\\\")

    return ax





def get_total_diffs(data_name, compared_alg, baseline_alg,
                    start_tp=0, end_tp=0,
                    normalise_per_100k=False):
    """
    For each algorithm in algs, returns all the differences between compared_alg and baseline_alg in the quantity {data_name} between tiempoints start_tp and end_tp inclusive.

    data_name (str): the name of quantitiy/timeseries we are interested in
    compared_alg (str): the name of the algorithm from whose results we will be subtracting values to get the differences (X in X-Y)
    baseline_alg (str): the name of the algorithm whose results we use to subtract with (Y in X-Y)
    start_tp: inclusive bound for the start of the sum
    end_tp: inclusive bound for the end of the sum
    normalise_per_100k (bool): whether to deal with the timeseries in terms of raw numbers, or as rates
    
    Returns:  Returns:    [list of difference-sums], including each param-seed pair that is successfully paired between the two algs, 
                set(unpaired param-seed pairs for compared), 
                set(unpaired param-seed pairs for baseline)
    
    """
    #Check correctness of parameters
    assert data_name in data_names
    assert compared_alg in screening_algorithms
    assert baseline_alg in screening_algorithms
    assert start_tp>=0 and start_tp<=end_tp

    #Find all the timeseriess of differences in dataname between the two algorithms
    difference_timeseriess, unpairedcompared, unpairedbaseline = get_paired_difference_tss(data_name, normalise_per_100k, compared_alg, baseline_alg)

    #Find the sums for each difference timeseries
    difference_sums = []
    for seed, param_index in difference_timeseriess.keys():
        dts = difference_timeseriess[(seed, param_index)]
        difference_sums.append(sum(dts[start_tp: end_tp+1]))

    return difference_sums,unpairedcompared, unpairedbaseline


def get_alg_comparison_grid(axs,algs, alg_colors,
                            data_name, start_tp = 0, end_tp=0, 
                            normalise_per_100k=False,
                            significance=0.05):
    """
    Plots (onto {ax}) a full comparison between all the algorithms in {algs}, in terms of quantity {data_name} added up in timepoint range [start_tp, end_tp]. 
    """
    #Assert parameter correctness (some assertations of parameter correctness are delegated to the start of functions called by this one)
    assert len(axs.shape) == 2 #2-dimensional plot...
    assert axs.shape[0] >= len(algs) #...with enough rows
    assert axs.shape[1] >= len(algs) #... and enough columns

    #Plot the figure, square by square
    min_histogram_x, max_histogram_x = 0,0 #these will be populated as we generate the histgrams and used later to uniformly scale the horizontal axis of the sqaures in which there are histograms
    min_std, max_std = 10000,0 #track the standard deviations of each set of values over which we test, for accurate power tests
    for i in tqdm(range(len(algs))):
        for j in range(len(algs)):
            ax=axs[i,j]
            ax.set_yticks([])
            ax.set_xticks([])
            ax.set_axis_off()

            #Load up relevant algorithms for this square
            alg1 = algs[i] #TODO: maybe need to switch algs 1 and 2
            alg2 = algs[j]

            #Sqaure is treated differently depending on its position in the figure
            if i<j:
                #Sqaures above the diagonal get a histogram of sum-differences between the two algorithms
                total_diffs, unpairedcompared, unpairedbaseline = get_total_diffs(data_name, alg2, alg1, 
                                              start_tp, end_tp, normalise_per_100k) 
                if len(unpairedcompared)>0 or len(unpairedbaseline)>0:
                    print(f"Failed to pair some of {alg1} and {alg2}'s runs. {len(total_diffs)} runs were still paired successfully between the algorithms.")
                
                ax.hist(total_diffs, bins=12, density=True, color='deepskyblue') #TODO: could this color be guided by the 'winning' algorithm?

                histogram_height = np.max(np.histogram(total_diffs, bins=12, density=True)[0])
                ax.vlines(0,0,histogram_height, colors='black', linewidth=1)

                min_histogram_x = min(min(total_diffs), min_histogram_x)
                max_histogram_x = max(max(total_diffs), max_histogram_x)

                #Update standard deviations
                std = np.std(total_diffs)
                max_std = max(max_std, std)
                min_std = min(min_std, std)
            elif i>j:
                #Sqaures below the diagonal get a p value and colouring to determine which algorithm is better
                total_diffs, _, _ = get_total_diffs(data_name, alg2, alg1, 
                                                    start_tp, end_tp, normalise_per_100k) #No need to check about unpaired runs as we already do so for the upper triangular part of the figure
                ttest_result = stats.ttest_rel(total_diffs, 0, alternative='two-sided')
                pvalue = ttest_result.pvalue
                statistic = ttest_result.statistic

                #Color the square if pvalue is significant
                color='none'
                greens = mpl.colormaps['Greens'] 
                reds = mpl.colormaps['Reds']        
                if pvalue<significance:
                    #colormap_point = 0.5*np.tanh(-np.log10(pvalue)/150)+0.2 #NOTE: the rate of change of color and max color may need to change to get the best resolution over our p values
                    logged = -np.log10(pvalue)
                    #print(logged)
                    colormap_point = max(0.75*np.tanh((logged-70)/30)+0.1, 0.2*np.tanh((logged-2)/8)+0.2, 0.2)
                    print(colormap_point)
                    if statistic>0:
                        color=greens(colormap_point)
                    else:
                        color=reds(colormap_point)

                    ax.add_patch(mpl.patches.Rectangle((0,0),
                                                        1,1,
                                                        fc=color,
                                                        ec='b',
                                                        lw=0) )


                #Plot p value
                if pvalue<significance:
                    ax.text(0.15,0.35, f"<0.001")
                else:
                    ax.text(0.25,0.35, "{:.3f}".format(pvalue))


                ax.vlines(0+0.01,0,1, colors='black', linewidth=0.5)
                ax.vlines(1-0.01,0,1, colors='black', linewidth=0.5)
                ax.hlines(0+0.01,0,1, colors='black', linewidth=0.5)
                ax.hlines(1-0.01,0,1, colors='black', linewidth=0.5)
                ax.set_xlim(xmin=0, xmax=1)
                ax.set_ylim(ymin=0, ymax=1)


            else:
                #Sqaures on the diagonal are just coloured according to algorithm (not for final figure, but for interpreting while debugging figure generation and for pasting into powerpoint for final adjustments)
                ax.add_patch(mpl.patches.Rectangle((0, 0),
                        1, 1,
                        fc = alg_colors[algs[i]],
                        ec = 'b',
                        lw = 0) )
                
                ax.set_xlim(xmin=0, xmax=1)
                ax.set_ylim(ymin=0, ymax=1)
    
    #Finally, rescale all axs relating to histograms to a uniform view (by plotting on lines which the axes then need to contain)
    for i in range(len(algs)):
        for j in range(len(algs)):
            ax=axs[i,j]
            if i<j:
                ax.hlines(0.000002, min_histogram_x, max_histogram_x, colors='black', linewidth=1)
                ax.set_xlim(xmin=min_histogram_x, xmax=max_histogram_x)

    print(f"Max std of differences encountered: {max_std}; min std of differences encountered: {min_std}.")

    return axs

def ttest_powerplot(ax, lower_std_bound, upper_std_bound, effect_size_lower=-4, effect_size_upper=4, alpha=0.01, nobs=44*5):
    """
    Plots power curves onto ax for a t test (power against ground truth mean difference). Plots two curves, for upper and lower bound of ground truth variance.
    effect_size_lower and effect_size_upper give the range of ground truth effect sizes (i.e. ground truth mean differences / standard deviation of empirical mean differences) over which we plot.
    alpha is the signficance level of our statistical test and nobs is the number of independant observations involved in each t test.
    """
    from statsmodels.stats.power import TTestPower

    analysis = TTestPower()
    effect_sizes = np.linspace(effect_size_lower, effect_size_upper, 5000) # Range of effect sizes 

    power = analysis.power(effect_size=effect_sizes, nobs=nobs, alpha=alpha, alternative='two-sided')
    ax.plot(effect_sizes*lower_std_bound, power, color='blue', lw=2, label=f'σ = {lower_std_bound}')
    ax.plot(effect_sizes*upper_std_bound, power, color='red', lw=2, label=f'σ = {upper_std_bound}')

    #Find the scale we need on the x axis
    upper_x_bound = effect_sizes[np.where(power[2500:] > 1-1e-8)[0][0] + 2500]*upper_std_bound*1.2 #the 1.2 mutliplier adds a small margin
    lower_x_bound = -1 * upper_x_bound #t test's power plot is symmetric
    ax.set_xlim(lower_x_bound,upper_x_bound)
    #ax.set_xticks(np.linspace(lower_x_bound//100, upper_x_bound, 10))

    #Other plot formatting
    ax.set_title(f'Power Curve for Paired T-Test (n = {nobs}, α = {alpha})')
    ax.set_xlabel('Ground Truth Mean Difference')
    ax.set_ylabel(f'Power of Paired T Test, as performed (α = {alpha}, n={nobs})')
    plt.legend()
    ax.set_yticks(np.arange(0,1,0.1))
    ax.grid(True)

    return ax
    


def get_elimination_table(algs, csv_filename, 
                          data_name='inc_cancers_allpop_alltypes', start_tp=240, end_tp=243,
                          normalise_per_100k=True, target_sum=4,
                        vacc_levels = ['_LV', '', '_HV']):
    """
    Saves a csv that forms a table of values relevant to cervical cancer elimination under different algorithms and vaccination levels.

    algs: set of screening algorithms to collect results over
    csv_fileaname: name of the file to which to save the generated results
    data_name: the quantity to compute sums of for each algorithm (changeable to focus, for example, on just unvaccinated subpopulation)
    start_tp: inclusive lower bound for the sum (defaults to start of 2040 for a simulation starting at 1980 for a sim with dt=0.25)
    end_tp: inclusive upper bound for the sum (defaults to end of 2040 (i.e. 2040.75) for a simulation starting at 1980 for a sim with dt=0.25)
    normalise_per_100k: whether all values should be normalised per 100k before adding up
    target_sum: the value which we want the sums to be strictly less than. If all sums for a particular alg at a particular vacc level are strictly below {target_sum}, then we write down an empirical probability of 1 of reaching the target sum level
    vacc_levels: vaccination levels over which we are repeating the results (defaults to all simulated vacc levels)

    Saves a csv file with one row for each algorithm, and one column-bunch for each vacc_level. ]
    Each column bunch contains columns for (LQ, Median, UQ) data_name sum between timepoints, and then the proportion of alg runs for that vacc level that got a sum under the target_sum
    """
    tabular_data = []

    #Add column headings
    row = ['alg']
    for vacc_level in vacc_levels:
        row.append(f"LQ ({vacc_level})")
        row.append(f"Median ({vacc_level})")
        row.append(f"UQ ({vacc_level})")
        row.append(f"P(less than target {target_sum}) ({vacc_level})")
    tabular_data.append(row)
    
    #Populate rest of rows of table
    for alg in tqdm(algs):
        row=[alg] #starting off row with the row heading
        for vacc_level in vacc_levels:
            totals = get_simple_totals(data_name, start_tp, end_tp, normalise_per_100k, algs=[f"{alg}{vacc_level}"])[f"{alg}{vacc_level}"]
            totals=np.array(totals) #needed for the following processing
            row.append("{:.2f}".format( np.percentile(totals, 25) ))
            row.append("{:.2f}".format( np.percentile(totals, 50) ))
            row.append("{:.2f}".format( np.percentile(totals, 75) ))
            row.append("{:.3f}".format( np.count_nonzero(totals<target_sum) / len(totals) ))
        tabular_data.append(row)

    #Save table to csv
    with open(csv_filename, 'w') as f:
        csvwriter = csv.writer(f, delimiter=',')
        csvwriter.writerows(tabular_data)









def plot_missingness(algs = screening_algorithms):
    """
    For all algorithms in screening_algorithms, loads the file and searches for each parameterisation and seed that indexes the data. 
    Plots grid of seeds on x axis, params on y axis, and squares are highlighted in red if they don't have all the algorithms represented in them - and then we print out which algorithms are semi-represetned for a given pair.
    """
    #Populate which seeds and params each alg has done, paired up, and also the total set of seeds and params used across everything
    
    seed_param_tuples_by_alg = {alg:[] for alg in algs}
    seeds = [] #needs to be ordered, hence list, but not to contain duplicates
    params = []
    for alg in algs:
        print(alg)
        try:
            with open(f"{alg}.pickle", "rb") as f:
                seed_param_tuples = pickle.load(f)["popsize_allpop"].keys() #the specific quantity being loaded is irrelevant here; as we assume that if one quantity is saved from a particular run, all quantities are successfully saved, and that data is not deleted from the files
                seed_param_tuples = set(seed_param_tuples)

                seed_param_tuples_by_alg[alg] = seed_param_tuples
                
                seeds_used_here = {seed for seed, _ in seed_param_tuples}
                seeds = list(set(seeds).union(seeds_used_here))

                params_used_here = {param for _, param in seed_param_tuples}
                params = list(set(params).union(params_used_here))
        except:
            print(f"Unable to open file {alg}.pickle for algorithm {alg}; all data marked red for this algorithm.")


    #Populate grid
    grid = np.zeros(shape=(len(seeds), len(params))) #assumes {seeds} and {params}
    for seed_index in range(len(seeds)):
        seed = seeds[seed_index]
        for param_index in range(len(params)):
            param = params[param_index]

            offending_algs = []
            for alg in algs:
                if (seed, param) not in seed_param_tuples_by_alg[alg]:
                    offending_algs.append(alg)
            
            if len(offending_algs)>0:
                grid[seed, param] = 1
                print(f"Seed {seed}, param {param} not represented by algs {offending_algs}")
    
    #Plot grid
    plt.imshow(grid)
    plt.xticks(params)
    plt.yticks(seeds)
    plt.show()


    #TODO: make this. determine the semi-represented algrioithms by just lookinga tone of the timeseries (clearly if you have one timseries tou have them all)



###- Running a simulation and saving its raw timeseries in relevant pickle file-###
def run_sim_and_save_raw_result(provided_base_pars, seed:int,
                                final_cal_data, par_labels,
                                alg_name
                                ):
    """
    Runs a single HPVsim simulation with {base_pars} and RNG seed {seed}, over all parameterisations defined in {(final_cal_data, par_labels)}, and saving into pickle file f"{alg_name}.pickle".

    base_pars: full parameterisation of HPVsim excluding calibrated parameters - INCLUDING the interventions we are passing to the model; {base_pars} defines the non-calibrated parameters of our model including fully specifying the screening algorithm we are modelling
    seed: RNG seed for simulation
    final_cal_data: a list of parameter tuples [(v11,v12,...,v1p),...,(vn1,vn2,...,vnp)] where there are p calibrated parameters and n parameterisations
    par_labels: the internal HPVsim name for each of the p calibrated parameters, corresponding to the tuple orderings in {final_cal_data}
    alg_name: the name of the algorithm represented by {base_pars}; raw results from the simulation run will be saved to f"{alg_name}.pickle"
    """
    num_params = len(final_cal_data) #number of parameterisations which make up the ensemble model we are using
    for i in tqdm(range(num_params)):
        cal_params = final_cal_data[i][0] #specific parametersation of this iteration (note final_cal_data[i] is a tuple (parameterisation tuple, GOF, order statistic of GOF within the calibration that generated it, ID of calibration where the parameterisation was sampled ))
        tmp_base_pars = deepcopy(provided_base_pars) #make deep copy of provided {base_pars} to add specific calibration parameters and logger to it without changing the original copy passed into this function


        #Set seed
        tmp_base_pars['rand_seed'] = seed*num_params + i #this ensures that we give HPVsim a unique random seed for each parameterisation (seed fixed) and for each seed (parameterisation fixed); so no two runs - unless both seed and parameterisation are the same - will have the same HPVsim seed, and therefore we can assume independance 

        #Set up logging
        logger, log = make_logging_intervention_for_result_gen()
        tmp_base_pars['interventions'].append(logger)

        #Set non-genotype calibrated parameters to this iteration's parameterisation
        tmp_base_pars['beta'] = cal_params[par_labels.index('params_beta')]
        tmp_base_pars['f_cross_layer'] = cal_params[par_labels.index('params_f_cross_layer')]
        tmp_base_pars['m_cross_layer'] = cal_params[par_labels.index('params_m_cross_layer')]

        #Set up {tmp_base_pars} to allow for specification of genotype parameters
        tmp_base_pars['genotype_pars'] = sc.objdict() #initialise genotype parameters within hpvsim
        for g in tmp_base_pars['genotypes']:
            tmp_base_pars['genotype_pars'][g] = get_genotype_pars(genotype=g)

        #Set genotype calibrated parameters to this iteration's parameterisation
        tmp_base_pars['genotype_pars']['hpv16']['cin_fn']['k'] = cal_params[par_labels.index('params_hpv16_cin_fn_k')]
        tmp_base_pars['genotype_pars']['hpv16']['dur_cin']['par1'] = cal_params[par_labels.index('params_hpv16_dur_cin_par1')]

        tmp_base_pars['genotype_pars']['hpv18']['cin_fn']['k'] = cal_params[par_labels.index('params_hpv18_cin_fn_k')]
        tmp_base_pars['genotype_pars']['hpv18']['dur_cin']['par1'] = cal_params[par_labels.index('params_hpv18_dur_cin_par1')]
        
        tmp_base_pars['genotype_pars']['hi5']['cin_fn']['k'] = cal_params[par_labels.index('params_hi5_cin_fn_k')]
        tmp_base_pars['genotype_pars']['hi5']['dur_cin']['par1'] = cal_params[par_labels.index('params_hi5_dur_cin_par1')]
        tmp_base_pars['genotype_pars']['hi5']['rel_beta'] = cal_params[par_labels.index('params_hi5_rel_beta')]

        tmp_base_pars['genotype_pars']['ohr']['cin_fn']['k'] = cal_params[par_labels.index('params_ohr_cin_fn_k')]
        tmp_base_pars['genotype_pars']['ohr']['dur_cin']['par1'] = cal_params[par_labels.index('params_ohr_dur_cin_par1')]
        tmp_base_pars['genotype_pars']['ohr']['rel_beta'] = cal_params[par_labels.index('params_ohr_rel_beta')]

        #Initialise and run sim itself
        sim = hpv.Sim(tmp_base_pars)
        sim.run()

        #Extract raw results from sim and save to relevant file
        save_timeseries_from_log(log, seed, i, alg_name)


###- Running a simulation and saving its raw timeseries in relevant pickle file-###
def run_sim_and_get_infection_histogram(seed:int, 
                                        age_bins, snapshot_tps,
                                        final_cal_data=None, par_labels=None,
                                        genotypes = [True, True, True, True],
                                        sex = [True, False],
                                        percentage = True,
                                        inc_vacc = True, inc_unvacc = True
                                        ):
    """
    Runs a single HPVsim simulation with {base_pars} and RNG seed {seed}, over each parameterisation defined in {(final_cal_data, par_labels)} for standard interventions (NHS 2025 screening and all vaccination) between 1980 and 2025. Records HPV infection prevalence of all population at each timepoint in {snapshot_tps}, recording as a histogram split into bins defined by {age_bins}.

    Infection prevalence for a given genotype is defined as the percentage of people with the INFECTIOUS state for that genotype, to be consistent with what testing could pick up in the real world (as this function is to be used for validation against real-world data).

    seed: RNG seed for simulation
    age_bins: List of ints [a1,a2,a3,...,an] where our histogram of prevalences by age are [0,a1), [a1,a2),...,[an-1,an)
    snapshot_tps: list of ints [t1,...,tk] where at each ti we record a snapshot of HPV infection prevalences by age
    final_cal_data: a list of parameter tuples [(v11,v12,...,v1p),...,(vn1,vn2,...,vnp)] where there are p calibrated parameters and n parameterisations. If None, loads in defaults locally.
    par_labels: the internal HPVsim name for each of the p calibrated parameters, corresponding to the tuple orderings in {final_cal_data}. If None, loads in defaults locally.
    genotypes: boolean list of 4 elements where ith element is whether we are counting the ith genotype of ["HPV 16", "HPV 18", "HI5", "OHR"] in our HPV prevalence we are recording
    sex: boolean list of [Whether to include Women in the sum, whether to include men in the sum]
    percentage: whether to record values as absolute counts of infection or as percentages of population in the age bracket
    inc_vacc: whether vaccinated individuals should be counted 
    inc_unvacc: whether unvaccinated individuals should be counted

    Returns: {tp: {age_bin_upper_bound: [list of observed prevalences over simulations]}}

    """
    from basePars import base_pars

    #Asserting parameter correctness, and loading in default calibration results if needed for model running 
    assert (final_cal_data is not None and par_labels is not None) or (final_cal_data is None and par_labels is None) #we can't have one parameter without the other, so either define both or define neither (and if neither is defined, we load them in: below)
    if final_cal_data is None or par_labels is None: 
        #Load in calibrated parameter sets
        with open('finalCalibration.pickle', 'rb') as file:
            loadeddata = pickle.load(file)
        final_cal_data = loadeddata['final_cal_data'] #this is a list of parameter-tuples, so has a fixed ordering
        par_labels = loadeddata['par_labels']

    #Define the variable to store the data we accumulate and then return
    all_prevalence_logs = {tp: {age_upper_bound:[] for age_upper_bound in age_bins} for tp in snapshot_tps}

    #Define function to be used for snapshotting
    def make_snapshot_logs(sim):
        if sim.t==0:
            sim.prevalence_logs = {tp: {age_upper_bound:0 for age_upper_bound in age_bins} for tp in snapshot_tps}
    make_snapshot_logs.label='make_snapshot_logs'

    def prevalence_snapshotter(sim):
        tp = sim.t
        if tp in sim.prevalence_logs.keys():
            #If we are recording things as a population percentage, record population size in each age bracket
            if percentage:
                pop_sizes = {age_upper_bound:0 for age_upper_bound in age_bins}

            for i in range(sim.n): #iterate through every person
                #Work out whether to exclude according to vaccination status
                vaccinated = sim.people.vaccinated[i]
                if (inc_vacc and vaccinated) or (inc_unvacc and (not vaccinated)):
                    exclude_by_vacc_status = False
                else:
                    exclude_by_vacc_status = True

                if sim.people.alive[i] and sex[int(sim.people.sex[i])] and (not exclude_by_vacc_status): #only count currently alive people and those of a sex we are logging (sim.people.sex[i]==0 => ith agent is a woman)
                    scale = sim.people.scale[i]
                    age = sim.people.age[i]
                    infectious = np.dot(sim.people.infectious[:,i], genotypes) > 0 #{infectious} assigned True iff agent is infectious with at least one of the genotypes of interest (defined in {genotypes})

                    #Find the age bin we are meant to be in
                    correct_age_bin_upper_bound = age_bins[-1]
                    for abub in age_bins[::-1]: #Iterate through age bins in reverse. Every time the upper bound of the age bin is larger than this agent's age, we put the agent into that age bin. This will continue until we are in the lowest age bin the agnet can be in; that will then be the correct bin
                        if age<abub:
                            correct_age_bin_upper_bound = abub

                    #Add to infections if infectious
                    if infectious:
                        sim.prevalence_logs[tp][correct_age_bin_upper_bound] += scale
                    
                    #If we are dividing by population size to get a prevalence percentage, add to the population size accordingly
                    if percentage:
                        pop_sizes[correct_age_bin_upper_bound] += scale  

            #Divide prevalence counts by population size if needed
            if percentage:
                for abub in age_bins:
                    sim.prevalence_logs[tp][abub] /= pop_sizes[abub]
    prevalence_snapshotter.label='prevalence_snapshotter'


    #Set up simulation base parameters
    base_pars = deepcopy(base_pars)
    base_pars['end']=2025
    base_pars['interventions'] = [make_snapshot_logs] + NHS_2025_lambdamu.get_interventions(l=1, m=1) + NHS_Vacc.vaccinations + [prevalence_snapshotter]
    

    #Run all the simulations
    num_params = len(final_cal_data) #number of parameterisations which make up the ensemble model we are using
    for i in tqdm(range(num_params)):
        cal_params = final_cal_data[i][0] #specific parametersation of this iteration (note final_cal_data[i] is a tuple (parameterisation tuple, GOF, order statistic of GOF within the calibration that generated it, ID of calibration where the parameterisation was sampled ))
        tmp_base_pars = deepcopy(base_pars) #make deep copy of provided {base_pars} to add specific calibration parameters and logger to it without changing the original copy passed into this function

        #Set seed
        tmp_base_pars['rand_seed'] = seed*num_params + i #this ensures that we give HPVsim a unique random seed for each parameterisation (seed fixed) and for each seed (parameterisation fixed); so no two runs - unless both seed and parameterisation are the same - will have the same HPVsim seed, and therefore we can assume independance 

        #Set non-genotype calibrated parameters to this iteration's parameterisation
        tmp_base_pars['beta'] = cal_params[par_labels.index('params_beta')]
        tmp_base_pars['f_cross_layer'] = cal_params[par_labels.index('params_f_cross_layer')]
        tmp_base_pars['m_cross_layer'] = cal_params[par_labels.index('params_m_cross_layer')]

        #Set up {tmp_base_pars} to allow for specification of genotype parameters
        tmp_base_pars['genotype_pars'] = sc.objdict() #initialise genotype parameters within hpvsim
        for g in tmp_base_pars['genotypes']:
            tmp_base_pars['genotype_pars'][g] = get_genotype_pars(genotype=g)

        #Set genotype calibrated parameters to this iteration's parameterisation
        tmp_base_pars['genotype_pars']['hpv16']['cin_fn']['k'] = cal_params[par_labels.index('params_hpv16_cin_fn_k')]
        tmp_base_pars['genotype_pars']['hpv16']['dur_cin']['par1'] = cal_params[par_labels.index('params_hpv16_dur_cin_par1')]

        tmp_base_pars['genotype_pars']['hpv18']['cin_fn']['k'] = cal_params[par_labels.index('params_hpv18_cin_fn_k')]
        tmp_base_pars['genotype_pars']['hpv18']['dur_cin']['par1'] = cal_params[par_labels.index('params_hpv18_dur_cin_par1')]
        
        tmp_base_pars['genotype_pars']['hi5']['cin_fn']['k'] = cal_params[par_labels.index('params_hi5_cin_fn_k')]
        tmp_base_pars['genotype_pars']['hi5']['dur_cin']['par1'] = cal_params[par_labels.index('params_hi5_dur_cin_par1')]
        tmp_base_pars['genotype_pars']['hi5']['rel_beta'] = cal_params[par_labels.index('params_hi5_rel_beta')]

        tmp_base_pars['genotype_pars']['ohr']['cin_fn']['k'] = cal_params[par_labels.index('params_ohr_cin_fn_k')]
        tmp_base_pars['genotype_pars']['ohr']['dur_cin']['par1'] = cal_params[par_labels.index('params_ohr_dur_cin_par1')]
        tmp_base_pars['genotype_pars']['ohr']['rel_beta'] = cal_params[par_labels.index('params_ohr_rel_beta')]

        #Initialise and run sim itself
        sim = hpv.Sim(tmp_base_pars)
        sim.run()

        #Extract prevalence snapshots/logs from sim and add to set of all prevalence logs
        prevalence_logs = sim.prevalence_logs
        for tp in snapshot_tps:
            for abub in age_bins:
                all_prevalence_logs[tp][abub].append(prevalence_logs[tp][abub])
        
    return all_prevalence_logs






if __name__=="__main__":
    #initialise_blank_ts_file()
    #quit()

    


    """
    #Uncomment this to generate and plot infection histograms 
    seed = 0
    tps = [4*(2016-1980)]#
    tps=[4*(2011-1980), 4*(2013-1980), 4*(2015-1980), 4*(2017-1980),4*(2019-1980), 4*(2020.5-1980)]
    age_bins = [16,20,100]#
    age_bins=[5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80]

    infection_hist_data = run_sim_and_get_infection_histogram(seed, age_bins, tps, inc_vacc=False, sex=[False, True])

    for tp in tps:
        csv_data = []
        for age_bin in age_bins:
            row = [age_bin]
            for val in infection_hist_data[tp][age_bin]:
                row.append(val)
            csv_data.append(row)
        
        with open(f"men_{1980+tp/4}.csv", "w") as f:
            writer = csv.writer(f)
            writer.writerows(csv_data)

    """
    


    
    """
    #Uncommenting this gives us all the algorithms
    algstoplot = ['5_5', '5_7', '5_10', '5_15', '5_20',
                               '7_7', '7_10', '7_15', '7_20',
                                      '10_10','10_15','10_20',
                                              '15_15','15_20',
                        '5plus7', '5plus10', '5plus15', '5plus20', #NOTE: there is no need to the diagnonal of the matrix here as well, because amounts to identical algorithms as the diagonal of the matrix above
                                    '7plus10', '7plus15', '7plus20',
                                            '10plus15','10plus20',
                                                        '15plus20',
                'none_none', #'none' indicates there is no (asymptomatic) screening at all (hence a lack of an interval itself)
                '5_none',
                '5plusnone']
    """

    """
    #Uncommenting this gives us a summary across all algorithms
    algstoplot = [  '5_5', '10_10', '15_15',
                    '5_7', '5_10', '5_15',
                    '10_15' ,
                    '5plus7', '5plus10', '5plus15',
                    '10plus15',
                    '5_none',
                    '5plusnone',
                    'none_none',  
                ]
    alg_colors = {'5_5': natureColorScheme['greens'][-1], '5_7': natureColorScheme['greens'][-2], '5_10': natureColorScheme['greens'][-3], '5_15': natureColorScheme['greens'][-4], 
                                      '10_10': natureColorScheme['yellows'][-1],'10_15': natureColorScheme['yellows'][-2],
                                              '15_15': natureColorScheme['bg2'][-1],
                        '5plus7': natureColorScheme['blues'][-2], '5plus10': natureColorScheme['blues'][-3], '5plus15': natureColorScheme['blues'][-4], 
                                            '10plus15': natureColorScheme['yellows'][-3],
                'none_none':natureColorScheme['reds'][-1], #'none' indicates there is no (asymptomatic) screening at all (hence a lack of an interval itself)
                '5_none':natureColorScheme['reds'][-5],
                '5plusnone':natureColorScheme['reds'][-3]}
    

    fig, ax = plt.subplots(1,1,figsize=(7,5))
    
    #plot_sum_barchart_all_vacc_levels(ax, alg_colors,'routine_screens_allpop', 200, 280, False,algstoplot ) #204 for 2031
    #plt.show() 

    show_quartiles = False; show_normal_CI = False #at most one of these can be True at once
    plot_quant_over_time(ax, 
                         data_name='inc_cancers_vaccpop_unvacctype',
                         #'prev_cancers_undiagnosed_after_5_years_vaccpop_vacctype',
                         algs=algstoplot, alg_colors= alg_colors, 
                         show_quartiles=show_quartiles, show_normal_CI=show_normal_CI, 
                         normalise_per_100k=True) 

    plt.xticks([80,120,160,200],[2020,2030,2040,2050])
    #plt.vlines(104, -100,50_000_000, color='black')
    #plt.hlines(1, 80, 200, color='black', linestyles='dotted')

    plt.xlim(80,200)

    #plt.ylim(0,2) #lim for cancer incidence
    #plt.yticks([0,0.5,1,1.5,2],[0,2,4,6,8]) #yticks for cancer incidence

    #plt.ylim(-0.1,1.5) #lim for cancer diagnoses
    #plt.yticks([0,0.5,1,1.5],[0,2,4,6]) #yticks for cancer diagnoses

    #plt.ylim(0,18.75) #lim for ud5y
    #plt.yticks(np.array([0,15,30,45,60,75])/4,[0,15,30,45,60,75]) #yticks for ud5y

    #plt.ylim(0,25) #lim for ud5y, unvacc only
    #plt.yticks(np.array([0,20,40,60,80,100])/4,[0,20,40,60,80,100]) #yticks for ud5y, unvacc only

    #plt.ylim(0,100/80) #lim for ud5y, vacc only
    #plt.yticks(np.array([0,20,40,60,80,100])/80,np.array([0,20,40,60,80,100])/20) #yticks for ud5y, vacc only

    #plt.ylim(-100,3_000) #lim for routine screens
    #plt.yticks(np.array([0,500,1000,1500,2000,2500,3000]),4*np.array([0,500,1000,1500,2000,2500,3000])) #yticks for routine screens

    #plt.ylim(-10_000,700_000) #lim for routine screens, unvacc only (when not per 100k)
    #plt.yticks(np.array([0,1,2,3,4,5,6,7])*100_000,np.array([0,1,2,3,4,5,6,7])*400_000) #yticks for routine screens, unvacc only (when not per 100k)


    #plt.ylim(-10_000,700_000) #lim for routine screens, vacc only (when not per 100k)
    #plt.yticks(np.array([0,1,2,3,4,5,6,7])*100_000,np.array([0,1,2,3,4,5,6,7])*400_000) #yticks for routine screens, vacc only (when not per 100k)

    #plt.legend()
    plt.show()
    """

    """
    #Uncommenting this gives us a summary across all algorithms, as above, but for LV
    algstoplot = ['5_5_LV', '5_7_LV', '5_10_LV', '5_15_LV', 
                                      '10_10_LV','10_15_LV',
                                              '15_15_LV',
                        '5plus7_LV', '5plus10_LV', '5plus15_LV', 
                                            '10plus15_LV',
                'none_none_LV', 
                '5_none_LV',
                '5plusnone_LV']
    alg_colors = {'5_5_LV': natureColorScheme['greens'][-1], '5_7_LV': natureColorScheme['greens'][-2], '5_10_LV': natureColorScheme['greens'][-3], '5_15_LV': natureColorScheme['greens'][-4], 
                                      '10_10_LV': natureColorScheme['yellows'][-1],'10_15_LV': natureColorScheme['yellows'][-2],
                                              '15_15_LV': natureColorScheme['bg2'][-1],
                        '5plus7_LV': natureColorScheme['blues'][-2], '5plus10_LV': natureColorScheme['blues'][-3], '5plus15_LV': natureColorScheme['blues'][-4], 
                                            '10plus15_LV': natureColorScheme['yellows'][-3],
                'none_none_LV':natureColorScheme['reds'][-1], #'none' indicates there is no (asymptomatic) screening at all (hence a lack of an interval itself)
                '5_none_LV':natureColorScheme['reds'][-5],
                '5plusnone_LV':natureColorScheme['reds'][-3]}
    """

    """
    #Uncommenting this gives us a summary across all algorithms, as above, but for HV
    algstoplot = ['5_5_HV', '5_7_HV', '5_10_HV', '5_15_HV', 
                                      '10_10_HV','10_15_HV',
                                        #      '15_15_HV',
                        '5plus7_HV', '5plus10_HV', '5plus15_HV', 
                                            '10plus15_HV',
               # 'none_none_HV', 
                '5_none_HV',
                '5plusnone_HV']
    alg_colors = {'5_5_HV': natureColorScheme['greens'][-1], '5_7_HV': natureColorScheme['greens'][-2], '5_10_HV': natureColorScheme['greens'][-3], '5_15_HV': natureColorScheme['greens'][-4], 
                                      '10_10_HV': natureColorScheme['yellows'][-1],'10_15_HV': natureColorScheme['yellows'][-2],
                                              '15_15_HV': natureColorScheme['bg2'][-1],
                        '5plus7_HV': natureColorScheme['blues'][-2], '5plus10_HV': natureColorScheme['blues'][-3], '5plus15_HV': natureColorScheme['blues'][-4], 
                                            '10plus15_HV': natureColorScheme['yellows'][-3],
                'none_none_HV':natureColorScheme['reds'][-1], #'none' indicates there is no (asymptomatic) screening at all (hence a lack of an interval itself)
                '5_none_HV':natureColorScheme['reds'][-5],
                '5plusnone_HV':natureColorScheme['reds'][-3]}
    """
    
    """
    #Uncommenting this gives us an overview of the spread of options
    algstoplot= ['5_5', '5_10', '5_15','5plus10', '5plus15',
               #  '10_10',#'10_15',
                 #'15_15',
                 #'5_none',
                #'none_none'
                ]
    """

    """
    #Uncommenting this gives us a look into indivudual status-wise vs cohort-wise interventions
    algstoplot= ['5_5','5_10', '5plus10',
                 '10_15', '10plus15',
                 '5_none', '5plusnone']
    """

    """
    #Uncommenting this gives us a look into intervention success over different vaccine uptakes
    algstoplot= ['5_5_LV','10_10_LV','none_none_LV',
                '5_5','10_10', 'none_none',
                 '5_5_HV','10_10_HV', 'none_none_HV',
                 ]
    """


    """
    #Uncomment this to get rough plots of timeseries
    fig, axs = plt.subplots(1,4)

    show_quartiles = False; show_normal_CI = True #at most one of these can be True at once
    plot_quant_over_time(axs[0], data_name='inc_infectious_allpop_alltypes',algs=algstoplot, alg_colors= alg_colors, show_quartiles=show_quartiles, show_normal_CI=show_normal_CI) 
    plot_quant_over_time(axs[1], data_name='inc_cancers_allpop_alltypes',algs= algstoplot, alg_colors= alg_colors, show_quartiles=show_quartiles, show_normal_CI=show_normal_CI)# THIS IS PER 3 MONTHS, MULTIPLY BY 4.
    plot_quant_over_time(axs[2], data_name='prev_cancers_undiagnosed_after_5_years_allpop_alltypes',algs=algstoplot, alg_colors= alg_colors, show_quartiles=show_quartiles, show_normal_CI=show_normal_CI)
    plot_quant_over_time(axs[3], data_name='routine_screens_allpop', algs=algstoplot, alg_colors= alg_colors, show_quartiles=show_quartiles, show_normal_CI=show_normal_CI)
    
    plt.legend()
    plt.show()
    """

    """
    #Uncomment this to plot sums from timeseries as barchart over all vaccination levels
    fig, ax = plt.subplots(1,1)

    algstoplot = ['5_5', '5_7', '5_10', '5_15', 
                                      '10_10','10_15',
                                              '15_15',
                        '5plus7', '5plus10', '5plus15', 
                                            '10plus15',
                'none_none', 
                '5_none',
                '5plusnone']
    alg_colors = {'5_5': natureColorScheme['greens'][-1], '5_7': natureColorScheme['greens'][-2], '5_10': natureColorScheme['greens'][-3], '5_15': natureColorScheme['greens'][-4], 
                                      '10_10': natureColorScheme['yellows'][-1],'10_15': natureColorScheme['yellows'][-2],
                                              '15_15': natureColorScheme['bg2'][-1],
                        '5plus7': natureColorScheme['blues'][-2], '5plus10': natureColorScheme['blues'][-3], '5plus15': natureColorScheme['blues'][-4], 
                                            '10plus15': natureColorScheme['yellows'][-3],
                'none_none':natureColorScheme['reds'][-1], #'none' indicates there is no (asymptomatic) screening at all (hence a lack of an interval itself)
                '5_none':natureColorScheme['reds'][-5],
                '5plusnone':natureColorScheme['reds'][-3]}

    plot_sum_barchart_all_vacc_levels(ax, alg_colors,'inc_cancers_allpop_alltypes', 204, 280, False,algstoplot )
    plt.show()
    """

    """
    #Uncomment this to get a big algorithm comparison grid    
    algstoplot = [  '5_5', '10_10', '15_15',
                    '5_7', '5_10', '5_15',
                    '10_15' ,
                    '5plus7', '5plus10', '5plus15',
                    '10plus15',
                    '5_none','5plusnone','none_none',  
                ]

    alg_colors = {'5_5': natureColorScheme['greens'][-1], '5_7': natureColorScheme['greens'][-2], '5_10': natureColorScheme['greens'][-3], '5_15': natureColorScheme['greens'][-4], 
                                      '10_10': natureColorScheme['yellows'][-1],'10_15': natureColorScheme['yellows'][-2],
                                              '15_15': natureColorScheme['bg2'][-1],
                        '5plus7': natureColorScheme['blues'][-2], '5plus10': natureColorScheme['blues'][-3], '5plus15': natureColorScheme['blues'][-4], 
                                            '10plus15': natureColorScheme['yellows'][-3],
                'none_none':natureColorScheme['reds'][-1], #'none' indicates there is no (asymptomatic) screening at all (hence a lack of an interval itself)
                '5_none':natureColorScheme['reds'][-5],
                '5plusnone':natureColorScheme['reds'][-3]}


    
    

    fig, axs = plt.subplots(len(algstoplot),len(algstoplot))
    get_alg_comparison_grid(axs, algstoplot, alg_colors,
                           'inc_cancers_allpop_alltypes', 240, 280, False,
                            significance=0.01
                            )
    plt.show()
    """

    #"""
    #Uncomment this to get the elimination probability table
    algstoplot = ['5_5', '5_7', '5_10', '5_15', 
                                      '10_10','10_15',
                                              '15_15',
                        '5plus7', '5plus10', '5plus15', 
                                            '10plus15',
                'none_none', 
                '5_none',
                '5plusnone']

    get_elimination_table(algstoplot, "elimination_probs_unvacconly_2045.csv", data_name='inc_cancers_unvaccpop_alltypes',
                          start_tp=260,end_tp=263)
    #"""

    """
    #Uncommenting this section plots a power plot for our t tests

    fig, ax = plt.subplots(1,1)
    scale_factor_to_get_per_100k = 1 # 59_000_000/100_000   #approx; we are rounding anyway so this is acceptable
    ttest_powerplot(ax, 350/scale_factor_to_get_per_100k, 1500/scale_factor_to_get_per_100k, effect_size_lower=-4, effect_size_upper=4, alpha=0.01, nobs=44*5)
    plt.show()
    """


    #TODO: i think plotting the vacc levels and infection incidence over time between teh three cases to show that in the short term yes the different levels of vaccination don't yield that different results by 2050, and yet even then we see some differences creeping into the sensitivtiy analysis - and then presumably if we run the simulations for longer we will get even bigger differences


    #TODO: I think that maybe the equity things should be plots like I have given jasmina, just giving a taste of different algorithm trends in the figure (similar to what I did with arun not showing all the signals, just show a sample of signals which represents the trends of teh whole population)
    #^ and then the probabilities of elimination should be tabulated with algorithms as rows, and columns grouped by vaccination uptake and then, for each vacc uptake value, containing LQ incidence over all of 2040, Median indicence over all of 2040, UQ incidence over all of 2040, and bolded probability.
    # then the equity tables are able to be made with my existing plotting functionality and the probabilities with a small change to my sum functionality. 

#I think I shopuld also look at equitability in terms of elimination probability by 2040 - splitting this by vacc and unvacc. WE see that the 5plusX algs are worse than the 5_x algs also in terms of prob of elimination if we look just at unvacc (with a bigger difference than if we looked at prob of elimination across the full pop). But I think rahter than repeating the same table lots of times, I should just embed the numbers in the text, accompanying a figure of the unvacc and vacc versions of the UDa5Y curves as a lil figure that references the big timeseries figure
